<?php

declare(strict_types=1);

namespace NiekNijland\RDW\Schema\Overrides;

use NiekNijland\RDW\Datasets\DatasetId;
use NiekNijland\RDW\Fields\RegisteredVehicleField;
use NiekNijland\RDW\Records\RegisteredVehicle;
use NiekNijland\RDW\Schema\CastType;
use NiekNijland\RDW\Schema\DatasetSchema;
use NiekNijland\RDW\Schema\FieldDescriptor;

final class RegisteredVehicleOverrides
{
    public static function schema(): DatasetSchema
    {
        return new DatasetSchema(
            datasetId: DatasetId::RegisteredVehicles,
            recordClass: RegisteredVehicle::class,
            fieldEnumClass: RegisteredVehicleField::class,
            fields: [
                new FieldDescriptor('kenteken', 'LicensePlate', 'licensePlate', CastType::String),
                new FieldDescriptor('voertuigsoort', 'VehicleType', 'vehicleType', CastType::String),
                new FieldDescriptor('merk', 'Brand', 'brand', CastType::String),
                new FieldDescriptor('handelsbenaming', 'CommercialName', 'commercialName', CastType::String),
                new FieldDescriptor('vervaldatum_apk', 'ApkExpiryDateLegacy', 'apkExpiryDateLegacy', CastType::Excluded),
                new FieldDescriptor('datum_tenaamstelling', 'RegistrationDateLegacy', 'registrationDateLegacy', CastType::Excluded),
                new FieldDescriptor('bruto_bpm', 'GrossBpm', 'grossBpm', CastType::Decimal),
                new FieldDescriptor('inrichting', 'Configuration', 'configuration', CastType::String),
                new FieldDescriptor('aantal_zitplaatsen', 'SeatCount', 'seatCount', CastType::Integer),
                new FieldDescriptor('eerste_kleur', 'PrimaryColor', 'primaryColor', CastType::String),
                new FieldDescriptor('tweede_kleur', 'SecondaryColor', 'secondaryColor', CastType::String),
                new FieldDescriptor('aantal_cilinders', 'CylinderCount', 'cylinderCount', CastType::Integer),
                new FieldDescriptor('cilinderinhoud', 'EngineDisplacement', 'engineDisplacement', CastType::Integer),
                new FieldDescriptor('massa_ledig_voertuig', 'EmptyMass', 'emptyMass', CastType::Integer),
                new FieldDescriptor('toegestane_maximum_massa_voertuig', 'PermittedMaximumMass', 'permittedMaximumMass', CastType::Integer),
                new FieldDescriptor('massa_rijklaar', 'ReadyToDriveMass', 'readyToDriveMass', CastType::Integer),
                new FieldDescriptor('maximum_massa_trekken_ongeremd', 'MaximumUnbrakedTowingMass', 'maximumUnbrakedTowingMass', CastType::Integer),
                new FieldDescriptor('maximum_trekken_massa_geremd', 'MaximumBrakedTowingMass', 'maximumBrakedTowingMass', CastType::Integer),
                new FieldDescriptor('datum_eerste_toelating', 'FirstAdmissionDateLegacy', 'firstAdmissionDateLegacy', CastType::Excluded),
                new FieldDescriptor('datum_eerste_tenaamstelling_in_nederland', 'FirstNetherlandsRegistrationDateLegacy', 'firstNetherlandsRegistrationDateLegacy', CastType::Excluded),
                new FieldDescriptor('wacht_op_keuren', 'IsWaitingForInspection', 'isWaitingForInspection', CastType::Boolean),
                new FieldDescriptor('catalogusprijs', 'CatalogPrice', 'catalogPrice', CastType::Decimal),
                new FieldDescriptor('wam_verzekerd', 'IsWamInsured', 'isWamInsured', CastType::Boolean),
                new FieldDescriptor('maximale_constructiesnelheid', 'MaximumDesignSpeed', 'maximumDesignSpeed', CastType::Integer),
                new FieldDescriptor('laadvermogen', 'LoadCapacity', 'loadCapacity', CastType::Integer),
                new FieldDescriptor('oplegger_geremd', 'SemiTrailerBrakedMass', 'semiTrailerBrakedMass', CastType::Integer),
                new FieldDescriptor('aanhangwagen_autonoom_geremd', 'TrailerAutonomousBrakedMass', 'trailerAutonomousBrakedMass', CastType::Integer),
                new FieldDescriptor('aanhangwagen_middenas_geremd', 'TrailerCenterAxleBrakedMass', 'trailerCenterAxleBrakedMass', CastType::Integer),
                new FieldDescriptor('aantal_staanplaatsen', 'StandingPlaceCount', 'standingPlaceCount', CastType::Integer),
                new FieldDescriptor('aantal_deuren', 'DoorCount', 'doorCount', CastType::Integer),
                new FieldDescriptor('aantal_wielen', 'WheelCount', 'wheelCount', CastType::Integer),
                new FieldDescriptor('afstand_hart_koppeling_tot_achterzijde_voertuig', 'DistanceCouplingToRear', 'distanceCouplingToRear', CastType::Integer),
                new FieldDescriptor('afstand_voorzijde_voertuig_tot_hart_koppeling', 'DistanceFrontToCoupling', 'distanceFrontToCoupling', CastType::Integer),
                new FieldDescriptor('afwijkende_maximum_snelheid', 'AlternativeMaximumSpeed', 'alternativeMaximumSpeed', CastType::Integer),
                new FieldDescriptor('lengte', 'Length', 'length', CastType::Integer),
                new FieldDescriptor('breedte', 'Width', 'width', CastType::Integer),
                new FieldDescriptor('europese_voertuigcategorie', 'EuropeanVehicleCategory', 'europeanVehicleCategory', CastType::String),
                new FieldDescriptor('europese_voertuigcategorie_toevoeging', 'EuropeanVehicleCategoryAddition', 'europeanVehicleCategoryAddition', CastType::String),
                new FieldDescriptor('europese_uitvoeringcategorie_toevoeging', 'EuropeanVariantCategoryAddition', 'europeanVariantCategoryAddition', CastType::String),
                new FieldDescriptor('plaats_chassisnummer', 'ChassisNumberLocation', 'chassisNumberLocation', CastType::String),
                new FieldDescriptor('technische_max_massa_voertuig', 'TechnicalMaximumMass', 'technicalMaximumMass', CastType::Integer),
                new FieldDescriptor('type', 'Type', 'type', CastType::String),
                new FieldDescriptor('type_gasinstallatie', 'GasInstallationType', 'gasInstallationType', CastType::String),
                new FieldDescriptor('typegoedkeuringsnummer', 'TypeApprovalNumber', 'typeApprovalNumber', CastType::String),
                new FieldDescriptor('variant', 'Variant', 'variant', CastType::String),
                new FieldDescriptor('uitvoering', 'Execution', 'execution', CastType::String),
                new FieldDescriptor('volgnummer_wijziging_eu_typegoedkeuring', 'EuTypeApprovalChangeSequenceNumber', 'euTypeApprovalChangeSequenceNumber', CastType::Integer),
                new FieldDescriptor('vermogen_massarijklaar', 'PowerToReadyMassRatio', 'powerToReadyMassRatio', CastType::Decimal),
                new FieldDescriptor('wielbasis', 'Wheelbase', 'wheelbase', CastType::Integer),
                new FieldDescriptor('export_indicator', 'IsExportRegistration', 'isExportRegistration', CastType::Boolean),
                new FieldDescriptor('openstaande_terugroepactie_indicator', 'HasOpenRecall', 'hasOpenRecall', CastType::Boolean),
                new FieldDescriptor('vervaldatum_tachograaf', 'TachographExpiryDateLegacy', 'tachographExpiryDateLegacy', CastType::Excluded),
                new FieldDescriptor('taxi_indicator', 'IsTaxi', 'isTaxi', CastType::Boolean),
                new FieldDescriptor('maximum_massa_samenstelling', 'MaximumCombinationMass', 'maximumCombinationMass', CastType::Integer),
                new FieldDescriptor('aantal_rolstoelplaatsen', 'WheelchairPlaceCount', 'wheelchairPlaceCount', CastType::Integer),
                new FieldDescriptor('maximum_ondersteunende_snelheid', 'MaximumAssistiveSpeed', 'maximumAssistiveSpeed', CastType::Integer),
                new FieldDescriptor('jaar_laatste_registratie_tellerstand', 'LastOdometerRegistrationYear', 'lastOdometerRegistrationYear', CastType::Integer),
                new FieldDescriptor('tellerstandoordeel', 'OdometerJudgement', 'odometerJudgement', CastType::String),
                new FieldDescriptor('code_toelichting_tellerstandoordeel', 'OdometerJudgementCode', 'odometerJudgementCode', CastType::String),
                new FieldDescriptor('tenaamstellen_mogelijk', 'CanBeTransferred', 'canBeTransferred', CastType::Boolean),
                new FieldDescriptor('vervaldatum_apk_dt', 'ApkExpiryDate', 'apkExpiryDate', CastType::CalendarDate),
                new FieldDescriptor('datum_tenaamstelling_dt', 'RegistrationDate', 'registrationDate', CastType::CalendarDate),
                new FieldDescriptor('datum_eerste_toelating_dt', 'FirstAdmissionDate', 'firstAdmissionDate', CastType::CalendarDate),
                new FieldDescriptor('datum_eerste_tenaamstelling_in_nederland_dt', 'FirstNetherlandsRegistrationDate', 'firstNetherlandsRegistrationDate', CastType::CalendarDate),
                new FieldDescriptor('vervaldatum_tachograaf_dt', 'TachographExpiryDate', 'tachographExpiryDate', CastType::CalendarDate),
                new FieldDescriptor('maximum_last_onder_de_vooras_sen_tezamen_koppeling', 'MaximumFrontAxleLoad', 'maximumFrontAxleLoad', CastType::Integer),
                new FieldDescriptor('type_remsysteem_voertuig_code', 'BrakeSystemTypeCode', 'brakeSystemTypeCode', CastType::String),
                new FieldDescriptor('rupsonderstelconfiguratiecode', 'TrackChassisConfigurationCode', 'trackChassisConfigurationCode', CastType::String),
                new FieldDescriptor('wielbasis_voertuig_minimum', 'WheelbaseMinimum', 'wheelbaseMinimum', CastType::Integer),
                new FieldDescriptor('wielbasis_voertuig_maximum', 'WheelbaseMaximum', 'wheelbaseMaximum', CastType::Integer),
                new FieldDescriptor('lengte_voertuig_minimum', 'LengthMinimum', 'lengthMinimum', CastType::Integer),
                new FieldDescriptor('lengte_voertuig_maximum', 'LengthMaximum', 'lengthMaximum', CastType::Integer),
                new FieldDescriptor('breedte_voertuig_minimum', 'WidthMinimum', 'widthMinimum', CastType::Integer),
                new FieldDescriptor('breedte_voertuig_maximum', 'WidthMaximum', 'widthMaximum', CastType::Integer),
                new FieldDescriptor('hoogte_voertuig', 'Height', 'height', CastType::Integer),
                new FieldDescriptor('hoogte_voertuig_minimum', 'HeightMinimum', 'heightMinimum', CastType::Integer),
                new FieldDescriptor('hoogte_voertuig_maximum', 'HeightMaximum', 'heightMaximum', CastType::Integer),
                new FieldDescriptor('massa_bedrijfsklaar_minimaal', 'OperationalMassMinimum', 'operationalMassMinimum', CastType::Integer),
                new FieldDescriptor('massa_bedrijfsklaar_maximaal', 'OperationalMassMaximum', 'operationalMassMaximum', CastType::Integer),
                new FieldDescriptor('technisch_toelaatbaar_massa_koppelpunt', 'TechnicalCouplingPointMass', 'technicalCouplingPointMass', CastType::Integer),
                new FieldDescriptor('maximum_massa_technisch_maximaal', 'TechnicalMaximumMassUpper', 'technicalMaximumMassUpper', CastType::Integer),
                new FieldDescriptor('maximum_massa_technisch_minimaal', 'TechnicalMaximumMassLower', 'technicalMaximumMassLower', CastType::Integer),
                new FieldDescriptor('subcategorie_nederland', 'NetherlandsSubcategory', 'netherlandsSubcategory', CastType::String),
                new FieldDescriptor('verticale_belasting_koppelpunt_getrokken_voertuig', 'CouplingPointVerticalLoadTrailer', 'couplingPointVerticalLoadTrailer', CastType::Integer),
                new FieldDescriptor('zuinigheidsclassificatie', 'EfficiencyClassification', 'efficiencyClassification', CastType::String),
                new FieldDescriptor('registratie_datum_goedkeuring_afschrijvingsmoment_bpm', 'BpmDepreciationApprovalDateLegacy', 'bpmDepreciationApprovalDateLegacy', CastType::Excluded),
                new FieldDescriptor('registratie_datum_goedkeuring_afschrijvingsmoment_bpm_dt', 'BpmDepreciationApprovalDate', 'bpmDepreciationApprovalDate', CastType::CalendarDate),
                new FieldDescriptor('gem_lading_wrde', 'AverageLoadValue', 'averageLoadValue', CastType::Decimal),
                new FieldDescriptor('aerodyn_voorz', 'AerodynamicEquipment', 'aerodynamicEquipment', CastType::String),
                new FieldDescriptor('massa_alt_aandr', 'AlternativeDriveAdditionalMass', 'alternativeDriveAdditionalMass', CastType::Integer),
                new FieldDescriptor('verl_cab_ind', 'HasExtendedCab', 'hasExtendedCab', CastType::Boolean),
                new FieldDescriptor('aantal_passagiers_zitplaatsen_wettelijk', 'LegalPassengerSeatCount', 'legalPassengerSeatCount', CastType::Integer),
                new FieldDescriptor('aanwijzingsnummer', 'DesignationNumber', 'designationNumber', CastType::String),
                new FieldDescriptor('api_gekentekende_voertuigen_assen', 'AxlesApiUrl', 'axlesApiUrl', CastType::Excluded),
                new FieldDescriptor('api_gekentekende_voertuigen_brandstof', 'FuelsApiUrl', 'fuelsApiUrl', CastType::Excluded),
                new FieldDescriptor('api_gekentekende_voertuigen_carrosserie', 'BodyworksApiUrl', 'bodyworksApiUrl', CastType::Excluded),
                new FieldDescriptor('api_gekentekende_voertuigen_carrosserie_specifiek', 'BodyworkSpecificationsApiUrl', 'bodyworkSpecificationsApiUrl', CastType::Excluded),
                new FieldDescriptor('api_gekentekende_voertuigen_voertuigklasse', 'VehicleClassesApiUrl', 'vehicleClassesApiUrl', CastType::Excluded),
            ],
        );
    }
}
